/**
 * The portable container — Dockerfile + .dockerignore, host-neutral. Every deploy target ships these
 * unchanged; only the host config (fly.toml / railway.json) and the CLI sequence differ. The image
 * runs `fastagent start /app` on `$PORT` with machinery under `$FASTAGENT_STATE_DIR` /
 * `$FASTAGENT_SECRETS_DIR` — standard container conventions, no host coupling.
 *
 * ONE deploy semantic: bake the WORKSPACE as the image (`COPY . .` — what you see is what ships),
 * with the agent at `./fastagent` inside it. The resolver in the image finds it exactly like dev does.
 * Deps install under `/app/fastagent`, and the Dockerfile lives there too — namespaced so it never
 * collides with one the workspace already owns.
 */
import { AGENT_DIR } from "../paths.ts";

export interface Artifact {
  path: string;
  content: string;
}

/** Fixed first-line prefix of a fastagent-generated Dockerfile — the ONE source both the generator (the
 *  `head` below) and the "is this ours?" check (cli deploy's kept-Dockerfile apt warn) share, so they
 *  can't drift into detecting a marker the generator no longer writes. */
export const GENERATED_DOCKERFILE_MARKER = "# Generated by `fastagent deploy`";

/** The ONE predicate for "did fastagent generate this Dockerfile?" — a generated file opens with the
 *  marker, so a hand-written one (or a file where the marker was dropped to take ownership) reads false.
 *  Both the "keep vs flag-as-stale" decision and the apt warning share this; a split would let them
 *  disagree on the same file (e.g. a marker not at byte 0). */
export function isGeneratedDockerfile(content: string): boolean {
  return content.startsWith(GENERATED_DOCKERFILE_MARKER);
}

/** First line of a generated `.dockerignore`. The workspace-root one is the single artifact deploy
 *  writes outside the agent dir, so it is never force-clobbered — which would strand OUR own file the
 *  day its content changes. The marker splits the two cases: ours is refreshed, yours is kept. */
const GENERATED_DOCKERIGNORE_MARKER = "# Generated by `fastagent deploy`";

/** Did fastagent generate this `.dockerignore`? (Same ownership rule as {@link isGeneratedDockerfile}.) */
export function isGeneratedDockerignore(content: string): boolean {
  return content.startsWith(GENERATED_DOCKERIGNORE_MARKER);
}

export interface ContainerInput {
  /** Whether the agent has a package.json (a code agent); else a pure markdown/skills agent. */
  hasPackageJson: boolean;
  /** The package manager the generated image targets: `bun` (packageManager: bun / a bun lockfile) gets an
   *  `oven/bun` base + `bun install` + `bun run fastagent`; otherwise npm on `node:22-slim`. */
  runtime: "node" | "bun";
  /** Whether the runtime's lockfile exists (package-lock.json for npm, bun.lock/bun.lockb for bun) — a
   *  frozen/ci install needs it; without it the build resolves versions at build time (not reproducible). */
  hasLockfile: boolean;
  /** For `runtime: "bun"`, the `FROM oven/bun:<tag>` version (from packageManager `bun@x`), else `"1"`. */
  bunVersion?: string;
  /** This fastagent version, to PIN the global install on the markdown path (reproducible redeploys). */
  version: string;
  /** Extra apt packages (fastagent.config deploy.apt) baked in for the agent's tools — git, ripgrep, …. */
  apt?: string[];
  /** Workspace-relative paths holding secrets that the NAME-based excludes below would miss — a
   *  `FASTAGENT_SECRETS_DIR` pointed at an in-tree directory not called `.secrets`. Preflight resolves
   *  them; excluding by path is what keeps `COPY . .` from baking a credential. */
  secretPaths?: string[];
  /** Whether the baked workspace ships a `.git` (preflight fact). When true, preflight has already
   *  merged "git" into `apt` (the write-back loop needs history + binary together); the plans word
   *  their runbook's freshness/write-back guidance from the same fact. */
  shipsGit?: boolean;
}

/** The apt layer (cached right after FROM). Debian default repos only. */
function aptLayer(packages?: string[]): string {
  return packages && packages.length > 0
    ? `RUN apt-get update \\
 && apt-get install -y --no-install-recommends ${packages.join(" ")} \\
 && rm -rf /var/lib/apt/lists/*
`
    : "";
}

function dockerfile(input: ContainerInput): string {
  // The whole workspace is baked at /app; deps install (and the local bin lives) under the agent dir
  // inside it, so every path below is prefixed with AGENT_DIR.
  const layoutNote = `The whole directory is the agent's workspace; the agent itself lives in ${AGENT_DIR}/.`;
  // apt layer right after FROM (cached across code changes): the agent's tools may shell out to git etc.,
  // which node:22-slim lacks. Debian default repos only — a package needing a custom repo (gh) or a
  // different base is the operator's own Dockerfile (kept if present). deploy.apt is package-name-validated.
  const apt = aptLayer(input.apt);
  // No package.json → pure markdown/skills agent: install the pinned CLI GLOBALLY and run `fastagent`
  // from PATH. That needs npm + a global bin, which live on node:22-slim, NOT on oven/bun — so this path
  // pins node:22-slim regardless of input.runtime (a stray bun lockfile with no package.json would
  // otherwise select a bun base here and crash the `npm i -g` build). input.runtime is meaningful only
  // for a code agent, so the bun-vs-node base below is scoped to that path.
  if (!input.hasPackageJson) {
    return `${GENERATED_DOCKERFILE_MARKER}. ${layoutNote}
# npm-based (a markdown/skills agent installs the pinned CLI globally; node:22-slim has npm).
FROM node:22-slim
${apt}WORKDIR /app
RUN npm i -g @fastagent-sh/fastagent@${input.version}
COPY . .
CMD ["fastagent", "start", "/app"]
`;
  }
  const isBun = input.runtime === "bun";
  const base = isBun ? `oven/bun:${input.bunVersion ?? "1"}` : "node:22-slim";
  const note = isBun
    ? "# Bun-based (packageManager: bun / a bun lockfile detected). fastagent runs under Bun (bun run)."
    : "# npm-based — for pnpm/yarn, adapt the install line + the lockfile COPY (corepack enable, etc.).";
  const head = `${GENERATED_DOCKERFILE_MARKER}. ${layoutNote}
${note}
FROM ${base}
${apt}WORKDIR /app
`;
  // Install ALL deps (no --omit=dev / --production): a repo-as-agent (e.g. an Astro site it operates on)
  // needs its full toolchain — the build/check tools that live in devDependencies — to do its work, and
  // we can't tell a repo-as-agent from a purpose-built agent, so the safe default keeps everything.
  // Only the AGENT's deps are installed — the workspace's own deps are the agent's runtime concern
  // (it can install them in its workspace when its job needs them).
  if (isBun) {
    // `--frozen-lockfile` needs bun.lock and hard-fails without it; fall back to a plain `bun install`
    // (resolves at build time — not reproducible; the CLI warns to commit the lockfile).
    // `bun run` executes the LOCAL node_modules/.bin entry only — never the registry. A bare
    // `bunx fastagent` would fall back to installing the npm package named `fastagent`, which is an
    // unrelated third-party package (ours is the scoped @fastagent-sh/fastagent).
    const install = input.hasLockfile ? "bun install --frozen-lockfile" : "bun install";
    return `${head}COPY ${AGENT_DIR}/package.json ${AGENT_DIR}/bun.lock* ./${AGENT_DIR}/
RUN cd ${AGENT_DIR} && ${install}
COPY . .
CMD ["sh", "-c", "cd ${AGENT_DIR} && bun run fastagent start /app"]
`;
  }
  // `npm ci` requires a lockfile and hard-fails without one (a common `init --no-install` agent);
  // fall back to `npm install` when there is none so the build never breaks. Caveat: `npm install`
  // resolves caret ranges at build time, so THIS branch is NOT reproducible — unlike the pinned
  // `npm ci` (lockfile) and pinned global (markdown) paths. The CLI warns to commit a lockfile.
  // The explicit local bin, not `npx fastagent`: npx falls back to fetching the npm package named
  // `fastagent` when the dep is absent — an unrelated third-party package (ours is scoped). The local
  // path fails fast and visibly instead.
  const install = input.hasLockfile ? "npm ci" : "npm install";
  return `${head}COPY ${AGENT_DIR}/package.json ${AGENT_DIR}/package-lock.json* ./${AGENT_DIR}/
RUN cd ${AGENT_DIR} && ${install}
COPY . .
CMD ["./${AGENT_DIR}/node_modules/.bin/fastagent", "start", "/app"]
`;
}

/** Patterns are RECURSIVE (`**​/`) on purpose — dockerignore patterns are root-anchored (unlike
 *  .gitignore), and a baked workspace can hold nested projects: a bare `node_modules` would upload
 *  their build-machine deps (macOS binaries!) and a bare `.env` would bake their secrets into the
 *  image. `.secrets`/`.state` are fastagent machinery — secrets travel through the host's secret
 *  store, state lives on the volume; neither may ever enter an image. `.cache` is generic hygiene
 *  (a baked project's own build cache), not a fastagent directory.
 *  `.git` is deliberately SHIPPED: the deployed agent's write-back (pull/commit/push) needs the
 *  repo's history+remote — the WYSIWYG bake's freshness/durability loop runs through git, driven by
 *  the agent itself, not by deploy machinery. Shipping `.git` is only half of that loop: preflight
 *  bakes the git BINARY into the generated image iff the workspace ships a `.git` (layout-neutral,
 *  the `shipsGit` fact); a non-git workspace that still needs git declares config.deploy.apt. */
const dockerignore = (input: ContainerInput): string =>
  DOCKERIGNORE_BASE +
  (input.secretPaths ?? [])
    .filter((p) => !p.startsWith(`${AGENT_DIR}/.secrets/`)) // already covered by **/.secrets
    .map((p) => `# resolved secrets path (FASTAGENT_SECRETS_DIR / FASTAGENT_AUTH_PATH)\n/${p}\n`)
    .join("");

const DOCKERIGNORE_BASE = `${GENERATED_DOCKERIGNORE_MARKER}. Delete this line to take ownership (deploy then keeps your file).
**/node_modules
**/.secrets
**/.state
**/.cache
**/.env
**/.env.*
!**/.env.example
**/*.log
# .git is deliberately shipped: the agent can pull to freshen content and push its work back
# (the generated image installs the git binary when this directory ships a .git; otherwise
# add deploy.apt ["git"]). For a smaller image with no git needs, add a ".git" line here.
`;

/**
 * The Dockerfile + ignore artifacts — spread into any host's artifact list. The Dockerfile is
 * namespaced under the agent dir (`fastagent/Dockerfile`) so it never collides with one the workspace
 * already owns. The ignore ships in TWO forms because context packing is host-CLI-owned and
 * inconsistent: (1) a ROOT `.dockerignore` — the only form flyctl/railway's own context packers
 * reliably read (kept if the workspace already has one — preflight then checks the machinery/secret
 * excludes it must carry) — and (2) a per-Dockerfile `fastagent/Dockerfile.dockerignore` for plain
 * docker/buildx builds. That root file is the ONE write deploy ever makes outside the agent dir, and
 * only at deploy time — without it the host CLI's packer would bake `.secrets/` into the image.
 */
export function containerArtifacts(input: ContainerInput): Artifact[] {
  const ignore = dockerignore(input);
  return [
    { path: `${AGENT_DIR}/Dockerfile`, content: dockerfile(input) },
    { path: ".dockerignore", content: ignore },
    { path: `${AGENT_DIR}/Dockerfile.dockerignore`, content: ignore },
  ];
}
